RFC: Vulnerability response runbook
bytecodealliance/rfcs pull request #20
Opened 2022-02-17 23:27 UTC by pchickey

This RFC proposes the vulnerability response process used by the Bytecode Alliance. It is structured as a runbook: a set of steps to be followed by the team responding to a discovered vulnerability.

It documents the process we followed for several different security advisories in Wasmtime and Lucet, for example:
https://github.com/bytecodealliance/wasmtime/security/advisories/GHSA-88xq-w8cq-xfg7
https://github.com/bytecodealliance/lucet/security/advisories/GHSA-hf79-8hjp-rrvq

2022-02-17 23:42 UTC, cfallin commented
On initial read, this looks really good and is quite complete!

Only thing I would add is that, if the vulnerability is in a Rust crate used by others, adding an entry to the [rustsec](https://github.com/rustsec/advisory-db) database is a good last step, after the CVE exists and is public. An example PR is [here](https://github.com/rustsec/advisory-db/pull/918) for last year's Cranelift CVE.

2022-02-18 00:01 UTC, bjorn3 commented on accepted/vulnerability-response-runbook.md
> +No individual or orginization is entitled to advanced disclosure. Advanced disclosure is
```suggestion
No individual or organization is entitled to advanced disclosure. Advanced disclosure is
```

2022-02-18 00:02 UTC, bjorn3 commented on accepted/vulnerability-response-runbook.md
> +not guaranteed to orginizations by membership in the Bytecode Alliance, nor is it exclusive
```suggestion
not guaranteed to organizations by membership in the Bytecode Alliance, nor is it exclusive
```

2022-02-18 00:05 UTC, bjorn3 commented on accepted/vulnerability-response-runbook.md
> +credited through their GitHub account.
If the individual who discovered the vulnerability doesn't have a github account what is the intended procedure? Provide their name and or website in the security advisory body? Or something else?

2022-02-21 19:27 UTC, jfoote approved these changes
Great baseline, well done @pchickey. I provided some spellcheck and also left one more substantive comment for your consideration.

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +Pick an individual who will track that the the entire process in this document isfollowed.
```suggestion
Pick an individual who will track that the entire process in this document is followed.
```

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +collaboate on a patch. GitHub will create a private fork of the repository on
```suggestion
collaborate on a patch. GitHub will create a private fork of the repository on
```

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +to resolve the vulnerabilty. This patch is automatically merged into the
```suggestion
to resolve the vulnerability. This patch is automatically merged into the
```

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +disclosure to trustworthy stakeholders. All stakeholders who recieve advanced disclosure
```suggestion
disclosure to trustworthy stakeholders. All stakeholders who receive advanced disclosure
```

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +disclosure date with stakeholders who have recieved advanced to understand their feasibility
```suggestion
disclosure date with stakeholders who have received advanced to understand their feasibility
```

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +The highes severity issue fixed in this release is <severity>, based on the
```suggestion
The highest severity issue fixed in this release is <severity>, based on the
```

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +Security Advisories may not assign blame to individuals or orginizations
```suggestion
Security Advisories may not assign blame to individuals or organizations
```

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +repositories, this guide may not work.
What should the reader do then? Maybe email security@bytecodealliance.org or ping folks on Zulip?

2022-02-21 19:27 UTC, jfoote commented on accepted/vulnerability-response-runbook.md
> +
This runbook is a great baseline for situations where a vulnerability has been reported or discovered privately. Should we add some brief guidance here on what a reader should do if an unpatched vulnerability is under active exploitation? Or if details of a private (or previously unknown) vulnerability were made public without coordination.

It could be something simple like this...
```suggestion
This document describes a series of steps to be followed by the Bytecode Alliance team when responding to a vulnerability that is discovered or reported privately.

This document does not cover cases where vulnerabilities are publicly disclosed without coordination. Or cases where unpatched vulnerabilities are under active exploitation. In those cases, contact security@bytecodealliance.org.
```
Or we could build out more process for these cases proactively.

2022-02-22 14:48 UTC, bnjbvr requested changes

2022-02-22 14:48 UTC, bnjbvr commented on accepted/vulnerability-response-runbook.md
> +is critical for maintaining trust in the Bytecode Alliance and its projects.
The cautiousness in this section is very close to "security through obscurity", as it tries to limit shared knowledge by asserting that this augments trust within the Alliance. The counter argument is that not trusting by default (and only include arbitrarily trusted people within the Alliance) sounds more like the opposite of trust.

Additionally, basing the selection of contacts on socialization has limits: it doesn't look like it would scale well with an increasing number of organizations in the Bytecode Alliance, times an increasing number of projects hosted by the Bytecode Alliance. In fact, it's unclear what should be the topics of socialization, and with which depth one should share implementation details that might also require an individual organization's discretion (think NDA).

I think there's an opportunity to do better here. We could imagine sharing light details with technical contacts of each Bytecode Alliance organization, on an internal but private secured channel (e.g. Signal, or any other equally valid broadcasting secured mechanism), that would make it possible for members to know if they're effectively affected or not. That could include, for example: patterns to look for in error logs, in the case of Wasmtime examples of `Config()` that would be affected by the security issue, metrics to watch and for which outliers could indicate potential exploitation in the wild. Other useful information could be shared according to the context around the security issue. After sharing that information, technical contacts could confirm whether they're impacted or not, and if impacted some extra actions could take place to ensure the issue might be mitigated for them (temporary patches for mitigations? getting early access to the CVE? request filters if Web/cloud providers? Each issue is likely to have its own set of temporary and useful countermeasures).

Of course this process doesn't pretend to be perfect and could be adapted. I think that in general, this would spur trust within the Bytecode Alliance and across its different members, by trusting by default instead of assuming the worst (notably that insiders would leak the exploit). Some entities might and will run Bytecode Alliance projects in production and they could be badly impacted if they had to schedule updates at the last minute, would they never hear about a security issue, because it was incorrectly decided (due to ineffective/incomplete/poor "socialization") that they would not be impacted.

2022-02-23 09:28 UTC, bnjbvr commented
(Forgot to say, sorry!) Great write-up, this definitely will streamline and structure the incident handling process!

2022-02-28 17:01 UTC, pchickey commented on accepted/vulnerability-response-runbook.md
> +repositories, this guide may not work.
```suggestion
repositories, this guide may not work. In situations not covered by this guide, please
email security@bytecodealliance.org to seek guidance.
```

2022-02-28 17:04 UTC, pchickey commented on accepted/vulnerability-response-runbook.md
> +credited through their GitHub account.
```suggestion
credited through their GitHub account. The incident manager can decide how to accommodate creditees
who do not wish to use the GitHub mechanism.
```

2022-02-28 17:11 UTC, pchickey commented on accepted/vulnerability-response-runbook.md
> +is critical for maintaining trust in the Bytecode Alliance and its projects.
I hear your concerns, but I don't think I am the right person to address them. When I wrote this up, I my goal was to document the principles we used to navigate this in the past, rather than come up with an improved system. I will have to defer to @tschneidereit and other Bytecode Alliance leaders on this topic.

2022-02-28 17:21 UTC, pchickey commented
@cfallin Thanks, added a RustSec database step to the final section. We haven't been consistent in publishing to that database, but there is no reason not to be.

2022-08-17 18:21 UTC, fitzgen commented on accepted/vulnerability-response-runbook.md
> +is critical for maintaining trust in the Bytecode Alliance and its projects.
This RFC has been open and stalled for a while now, and I think it has a lot of really good stuff in it that is helpful for the people dealing with these rare security bugs. No, this RFC does not have all the answers and there are improvements we can make. However, it is still a super helpful resource for when folks are caught up in the midst of a security bug. And there is no reason we can't further refine our processes with future RFCs.

With all that said, would you be okay if we moved to merge this RFC, @bnjbvr?

2022-08-18 09:56 UTC, bnjbvr commented on accepted/vulnerability-response-runbook.md
> +is critical for maintaining trust in the Bytecode Alliance and its projects.
Agreed that there's lots of goodness in this runbook!

I would be fine with merging, *if we removed those three paragraphs I commented about* (since there's been no discussion about the core issue I'm flagging here, and it looks quite important to me to, at the very least, discuss). Approving the RFC as it is right now would mean turning this into the default, widely accepted measure, and since communication has stalled as you point, anybody opening a PR to change that would likely face a similar stall situation, adding way more friction to changing the wording here. Does that sound reasonable?

2022-08-18 17:16 UTC, fitzgen commented on accepted/vulnerability-response-runbook.md
> +is critical for maintaining trust in the Bytecode Alliance and its projects.
That seems like a reasonable path forward to me. @pchickey sound good to you?

2022-08-18 18:26 UTC, pchickey commented on accepted/vulnerability-response-runbook.md
> +is critical for maintaining trust in the Bytecode Alliance and its projects.
Agreed, and done!

2022-08-18 18:40 UTC, bnjbvr approved these changes
Thanks a lot!

2022-08-18 18:53 UTC, pchickey commented
# Motion to finalize with a disposition to merge

This RFC was forgotten for a little while with one piece of unresolved feedback, which has now been resolved. We have been using it de-facto during the time it was open.

# Stakeholders sign-off

This effects all Bytecode Alliance projects so I've copied the biggest stakeholder list I could find (#14) and added some new folks. I apologize if I missed anyone, I am happy to add folks.

## Arm

* [ ] @akirilov-arm
* [ ] @sparker-arm

## DFINITY

* [ ] @granstrom

## Embark Studios

* [ ] @bnjbvr
* [ ] @repi

## Fastly

* [ ] @cfallin
* [ ] @sunfishcode 
* [ ] @fitzgen 
* [x] @pchickey 
* [ ] @peterhuene 
* [ ] @acfoltzer 
* [ ] @iximeow 
* [ ] @aturon 
* [ ] @cratelyn 
* [ ] @elliottt
* [ ] @jameysharp

## Google/Envoy

* [ ] @PiotrSikora

## Intel

* [ ] @mingqiusun
* [ ] @abrown 
* [ ] @jlb6740

## Microsoft

* [ ] @squillace

## Fermyon

* [ ] @bacongobbler
* [ ] @radu-matei

## Mozilla

* [ ] @julian-seward1 
* [ ] @yurydelendik

## IBM

* [ ] @uweigand

## wasmCloud

* [ ] @autodidaddict

## Unaffiliated

* [ ] @tschneidereit 
* [ ] @bjorn3

2022-08-18 23:42 UTC, fitzgen commented
As per the [RFC process](https://github.com/bytecodealliance/rfcs/blob/main/accepted/rfc-process.md#making-a-decision-merge-or-close) this RFC is entering its 10 day **final comment period**.

If no objections have been raised by **2022-08-28**, we will merge this RFC.

2022-08-18 23:51 UTC, radu-matei approved these changes

2022-08-19 09:46 UTC, bjorn3 approved these changes

2022-08-19 09:46 UTC, bjorn3 commented
@tschneidereit should be listed in the Fastly section, right?

2022-08-24 18:07 UTC, uweigand approved these changes

2022-08-29 20:25 UTC, fitzgen commented
The final comment period has elapsed without any objections, so I'm going to merge this!

2022-08-29 20:25 UTC, merged